const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync } = require('node:child_process');

test('runtime bootstrap preserves original app path and reuses the cached build', async t => {
  const { createPackage, extractFile } = await import('@electron/asar');
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'teams-omarchy-runtime-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const source = path.join(root, 'native app');
  const integration = path.join(root, 'integration');
  const fixture = path.join(root, 'fixture');
  fs.mkdirSync(path.join(source, 'resources'), { recursive: true });
  fs.mkdirSync(path.join(fixture, 'app'), { recursive: true });
  fs.mkdirSync(integration);
  fs.writeFileSync(path.join(fixture, 'package.json'), JSON.stringify({ name: 'teams-for-linux', version: '2.20.1', main: 'app/index.js' }));
  fs.writeFileSync(path.join(fixture, 'app/index.js'), '// fixture');
  const archive = path.join(source, 'resources/app.asar');
  await createPackage(fixture, archive);
  fs.writeFileSync(path.join(source, 'teams-for-linux'), '#!/bin/sh\nexit 0\n', { mode: 0o755 });
  fs.writeFileSync(path.join(source, 'resources/icon.png'), 'fixture');
  fs.copyFileSync(path.join(__dirname, '../src/prepare.cjs'), path.join(integration, 'prepare.cjs'));
  fs.symlinkSync(path.join(__dirname, '../node_modules'), path.join(integration, 'node_modules'));
  fs.writeFileSync(path.join(integration, 'settings.json'), JSON.stringify({ teamsDir: source }));
  const build = () => execFileSync(process.execPath, [path.join(integration, 'prepare.cjs')], { encoding: 'utf8' }).trim();
  const executable = build();
  assert.equal(build(), executable);
  assert.equal(fs.statSync(executable).mode & 0o777, 0o755);
  const bootArchive = path.join(path.dirname(executable), 'resources/app.asar');
  const bootstrap = extractFile(bootArchive, 'index.cjs').toString();
  assert.ok(bootstrap.includes(`setAppPath(${JSON.stringify(archive)})`));
  assert.ok(bootstrap.includes(JSON.stringify(path.join(integration, 'live-theme.cjs'))));
  assert.ok(bootstrap.includes(JSON.stringify(path.join(archive, 'app/index.js'))));
  assert.equal(JSON.parse(extractFile(bootArchive, 'package.json')).version, '2.20.1');
  assert.equal(fs.readlinkSync(path.join(path.dirname(executable), 'resources/icon.png')), path.join(source, 'resources/icon.png'));
  assert.equal(fs.readFileSync(path.join(source, 'teams-for-linux'), 'utf8'), '#!/bin/sh\nexit 0\n');
});
